{ pkgs, config, lib, ... }:
{
  home.username = "ajisrael";
  home.homeDirectory = "/home/ajisrael";
  home.stateVersion = "26.05";

  targets.genericLinux.enable = true;

  programs.home-manager.enable = true;

  programs.git = {
    enable = true;
    settings.user = {
      name = "Alex Israels";
      email = "43039187+ajisrael@users.noreply.github.com";
    };
  };

  # Key is named ~/.ssh/github (not a default identity file), so pin it to the
  # host - otherwise ssh only offers it when it is loaded into the agent.
  # enableDefaultConfig = false keeps home-manager from injecting its own
  # defaults; the "Host *" block below replicates them explicitly.
  programs.ssh = {
    enable = true;
    enableDefaultConfig = false;
    settings = {
      "*" = {
        ForwardAgent = false;
        AddKeysToAgent = "no";
        Compression = false;
        ServerAliveInterval = 0;
        ServerAliveCountMax = 3;
        HashKnownHosts = false;
        UserKnownHostsFile = "~/.ssh/known_hosts";
        ControlMaster = "no";
        ControlPath = "~/.ssh/master-%r@%n:%p";
        ControlPersist = "no";
      };
      "github.com" = {
        HostName = "github.com";
        User = "git";
        IdentityFile = "~/.ssh/github";
        IdentitiesOnly = true;
      };
    };
  };

  home.packages = [ pkgs.hello ];

  # zsh + oh-my-zsh + Powerlevel10k, mirroring the macOS dotfiles setup but
  # declarative: pkgs.zsh-powerlevel10k provides the theme (oh-my-zsh's
  # `custom` points at its share dir so ZSH_THEME="powerlevel10k/powerlevel10k"
  # resolves), autosuggestion/syntaxHighlighting come from their own HM
  # modules instead of omz plugins, and the repo-tracked personal.zsh is
  # sourced last via initContent (p10k.zsh config is loaded from there too).
  programs.zsh = {
    enable = true;
    enableCompletion = true;

    oh-my-zsh = {
      enable = true;
      plugins = [ "git" ];
      theme = "powerlevel10k/powerlevel10k";
      custom = "${pkgs.zsh-powerlevel10k}/share/zsh";
    };

    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;

    # initContent replaces the deprecated initExtra/initExtraFirst etc;
    # 500 = early (before completion/oh-my-zsh), 1500 = last. Keep the p10k
    # instant prompt close to the top of ~/.zshrc and source the repo's
    # personal.zsh at the very end (it loads ~/.p10k.zsh, so it must run
    # after the theme).
    initContent = lib.mkMerge [
      (lib.mkOrder 500 ''
        # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
        # Initialization code that may require console input (password prompts, [y/n]
        # confirmations, etc.) must go above this block; everything else may go below.
        if [[ -r "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
          source "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
        fi
      '')
      (lib.mkOrder 1500 ''
        source "$HOME/.zshrc.personal"
      '')
    ];
  };

  # tmux-sessionizer is on PATH so `bind f` (tmux neww tmux-sessionizer) works.
  home.sessionPath = [ "/home/ajisrael/arch-setup/config/tmux/tmux-scripts" ];

  # Live-editable configs: plain files in the repo, symlinked into ~/.config.
  # Editing the file in place is instantly picked up - no re-switch needed.
  home.file = let
    repo = "/home/ajisrael/arch-setup";
    link = path:
      config.lib.file.mkOutOfStoreSymlink "${repo}/config/${path}";
  in {
    ".ssh/config".force = true; # programs.ssh generates it; clobber the pre-flake file
    ".bashrc" = {
      source = link "bash/bashrc";
      force = true; # clobber the stock ~/.bashrc so home-manager owns it
    };
    ".bash_profile" = {
      source = link "bash/bash_profile";
      force = true; # login shells (tty1/ssh) delegate to ~/.bashrc
    };
    ".tmux.conf".source = link "tmux/tmux.conf";
    ".config/nvim".source = link "nvim"; # git submodule -> kickstart.nvim fork
    ".zshrc.personal" = {
      source = link "zsh/personal.zsh";
      force = true; # programs.zsh generates ~/.zshrc; this is the repo-owned fragment
    };
    ".p10k.zsh" = {
      source = link "zsh/p10k.zsh";
      force = true; # lives in the repo (generated by p10k configure); keep it tracked
    };
    ".config/hypr/hyprland.lua" = {
      source = link "hypr/hyprland.lua";
      force = true; # clobbers the auto-generated config from the first start-hyprland
    };
    ".config/hypr/hyprlock.conf".source = link "hypr/hyprlock.conf";
    ".config/hypr/hypridle.conf".source = link "hypr/hypridle.conf";
    ".config/hypr/hyprpaper.conf".source = link "hypr/hyprpaper.conf";
    ".config/kitty/kitty.conf".source = link "kitty/kitty.conf";
    ".config/mako/config".source = link "mako/config";
    ".config/wofi/config".source = link "wofi/config";
    ".config/wofi/style.css".source = link "wofi/style.css";
    ".config/waybar/config.jsonc".source = link "waybar/config.jsonc";
    ".config/waybar/style.css".source = link "waybar/style.css";
    # opencode: project-local configs promoted to global user config. Loaded by
    # opencode on startup; restart opencode after a switch to pick up changes.
    ".config/opencode/opencode.json".source = link "opencode/opencode.json";
    ".config/opencode/tui.json".source = link "opencode/tui.json";
  };
}
