general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/ajisrael/arch-setup/config/wallpapers/archeus-login-screen.png
    color = rgba(26, 27, 38, 1.0)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_family = Press Start 2P
    font_size = 48
    color = rgb(192, 202, 245)
    position = -24, 24
    halign = right
    valign = bottom
}

input-field {
    monitor =
    size = 260, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(255, 158, 100, 1.0)
    inner_color = rgba(26, 27, 38, 1.0)
    font_color = rgba(192, 202, 245, 1.0)
    position = 0, 8%
    halign = center
    valign = bottom
    placeholder_text = Password:
}
