general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/ajisrael/arch-setup/config/wallpapers/current.jpg
    color = rgba(30, 30, 46, 1.0)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_family = JetBrainsMono Nerd Font
    font_size = 72
    color = rgb(205, 214, 244)
    position = 0, 300
    halign = center
    valign = center
}
