general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/ajisrael/arch-setup/config/wallpapers/current.jpg
    color = rgba(30, 30, 46, 1.0)
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    font_family = JetBrainsMono Nerd Font
    font_size = 72
    color = rgb(205, 214, 244)
    position = 0, 300
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(137, 180, 250, 1.0)
    inner_color = rgba(30, 30, 46, 1.0)
    font_color = rgba(205, 214, 244, 1.0)
    position = 0, -60
    halign = center
    valign = center
    placeholder_text = Password:
}
